const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const INC_QUANTITY = "INC_QUANTITY";
const DEC_QUANITTY = "DEC_QUANTITY";
const DELETE_ALL = "DELETE_ALL";
export { ADD_ITEM, DELETE_ITEM, INC_QUANTITY, DEC_QUANITTY, DELETE_ALL };
